import { FastifyPluginCallback } from 'fastify'
import { fastifySwagger } from 'fastify-swagger'
import fp from 'fastify-plugin'

const swagger: FastifyPluginCallback = (fastify, options, done) => {
  return fastifySwagger(fastify, {
    routePrefix: '/doc',
    // openapi 3.0.3 options
    openapi: {
      info: {
        title: 'Stasher API',
        description: 'Autogenerated OpenAPI specification for Stasher App',
        version: '0.1.0'
      },
      servers: [ 
        { url: "http://127.0.0.1:3000" },
        { url: "https://jokerbe.herokuapp.com/" },
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT'
          }
        }
      },
    },

    uiConfig: {
      // docExpansion: 'full',
      deepLinking: false
    },
    staticCSP: true,
    transformStaticCSP: (header) => header,
    exposeRoute: true
  }, done)
}

export default fp(swagger, '3.x')
